name: login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 900
          style: normal
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 800
          style: normal
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
          style: normal
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
          style: normal
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic